language: node_js
node_js:
  - 0.12.0
  - 4.1.1
  - stable
after_success:
  - npm run coveralls
before_deploy:
  - npm --no-git-tag-version version 1.0.$TRAVIS_BUILD_NUMBER
deploy:
  provider: npm
  email: chris@cns.me.uk
  api_key:
    secure: MevJRVgA3bU93wQDNit8Hgdvau+uDgeyOq1TVxUcSIVqjg3rGqwMgW12jmxSS02Um0n2OaguJ9xPt6ggqPQlhntyl11jLFmqEKLMNaZSRgwRkojLeOW6/pmykoRvL8EJDG+iS9j652Ez6bd8JVJN4aMkgeTIjfBx5qDjvxqdmpCbR8uhzPY3sOhXmEQGCHz0clSzO/aP4wEmiJNDLd4B2seGV+XBPdvom6WR+53K+Qr18Z3QuWzlIGEGGNuD5JMcPcSsT6afmhSBzRMMyRzbyBuVLmsIaVrE+IyBM+co54+XFIDFc0o4rs1WlIzXszobk50SGKtp/El61PtP8ffGEpoDmhEEuGB+z9kiQfdRKCQep5Re2B4k8c9raLKH9/wuufRT/M4/0ASspEGmvByluLDCH3PB11DMuWBvRjeymdY77nUtMkAtAEqNDGAgEynlwQr1YGc3Pq5r5L9LQEUddykm122SC1wb2Fitrc84BpbM6PI072ai/dNgEQDHqRhRE7dB+x8LOddf7y3X9/iTU7we29C61P6QMln1qK0z7cNS4xKOW9qNzCYhpEhc1slIK+SGByS/E7ERXR2l2qhitodnmuX+UlLqlBJoTFxzvjlZFLH1bAecPSPeFRURNycYub/qbcd7PvSiy9aW+pqTABfUDyaumXj9EWLGjjzcS1I=
  skip_cleanup: true
  on:
    branch: master
    node_js: stable
